#pragma once

#include "ScrewExtendMicroConfig.h"

#define ELMG_TERMINAL_TRACE(...) ENGINE_TERMINAL_TRACE(__VA_ARGS__)
#define ELMG_TERMINAL_INFO(...) ENGINE_TERMINAL_INFO(__VA_ARGS__)
#define ELMG_TERMINAL_DEBUG(...) ENGINE_TERMINAL_DEBUG(__VA_ARGS__)
#define ELMG_TERMINAL_WARN(...) ENGINE_TERMINAL_WARN(__VA_ARGS__)
#define ELMG_TERMINAL_ERROR(...) ENGINE_TERMINAL_ERROR(__VA_ARGS__)
#define ELMG_TERMINAL_CRITICAL(...) ENGINE_TERMINAL_CRITICAL(__VA_ARGS__)

#define ELMG_CLIENT_TRACE(...) ENGINE_CLIENT_TRACE(__VA_ARGS__)
#define ELMG_CLIENT_INFO(...) ENGINE_CLIENT_INFO(__VA_ARGS__)
#define ELMG_CLIENT_DEBUG(...) ENGINE_CLIENT_DEBUG(__VA_ARGS__)
#define ELMG_CLIENT_WARN(...) ENGINE_CLIENT_WARN(__VA_ARGS__) 
#define ELMG_CLIENT_ERROR(...) ENGINE_CLIENT_ERROR(__VA_ARGS__)
#define ELMG_CLIENT_CRITICAL(...) ENGINE_CLIENT_CRITICAL(__VA_ARGS__)